#!/usr/bin/env bash
#transters a file from client to a server
echo $#
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	filepath=$1
	ip=$2
	username=$3
	sshkeypath=$4
	scp -o StrictHostKeyChecking=no -i "$sshkeypath" "$filepath" "$username"@"$ip":~/
fi
